In [ ]:
#@title
%%capture
!rm -rf *
!gdown 19b7ixRt9TU3Kb7r8NwiJ9UaK7Z34-9eH -O e03_ok.zip
!cd /content
!unzip e03_ok.zip
!pip install git+https://github.com/grading/gradememaybe.git

from IPython.display import YouTubeVideo
from gofer import ok

# 1 Upload do Arquivo

Use o espaço abaixo para fazer o upload do arquivo para o ambiente do Google Colab. Para isso você pode usar o comando `gdown` (lembre-se de colocar o sinal de exclamação `!` para chamar comandos na linha de comando, fora do Python).

In [ ]:
!gdown 1d3NbjXro_BfnYpFm66ETBfe7ubAZPAoL

Downloading...
From: https://drive.google.com/uc?id=1d3NbjXro_BfnYpFm66ETBfe7ubAZPAoL
To: /content/Iris.csv
100% 5.11k/5.11k [00:00<00:00, 7.49MB/s]


In [ ]:
ok.check('e03_1.py')

# 2 Leitura do Arquivo

Escreva um laço que leia todas as linhas do arquivo, criando uma lista numa variável de nome 'd0', onde cada elemento da lista é uma string que corresponde a uma linha do arquivo.

In [ ]:
d0 = open('/content/Iris.csv','r').readlines()
for line in d0:
  print(d0)


['Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species\n', '1,5.1,3.5,1.4,0.2,Iris-setosa\n', '2,4.9,3.0,1.4,0.2,Iris-setosa\n', '3,4.7,3.2,1.3,0.2,Iris-setosa\n', '4,4.6,3.1,1.5,0.2,Iris-setosa\n', '5,5.0,3.6,1.4,0.2,Iris-setosa\n', '6,5.4,3.9,1.7,0.4,Iris-setosa\n', '7,4.6,3.4,1.4,0.3,Iris-setosa\n', '8,5.0,3.4,1.5,0.2,Iris-setosa\n', '9,4.4,2.9,1.4,0.2,Iris-setosa\n', '10,4.9,3.1,1.5,0.1,Iris-setosa\n', '11,5.4,3.7,1.5,0.2,Iris-setosa\n', '12,4.8,3.4,1.6,0.2,Iris-setosa\n', '13,4.8,3.0,1.4,0.1,Iris-setosa\n', '14,4.3,3.0,1.1,0.1,Iris-setosa\n', '15,5.8,4.0,1.2,0.2,Iris-setosa\n', '16,5.7,4.4,1.5,0.4,Iris-setosa\n', '17,5.4,3.9,1.3,0.4,Iris-setosa\n', '18,5.1,3.5,1.4,0.3,Iris-setosa\n', '19,5.7,3.8,1.7,0.3,Iris-setosa\n', '20,5.1,3.8,1.5,0.3,Iris-setosa\n', '21,5.4,3.4,1.7,0.2,Iris-setosa\n', '22,5.1,3.7,1.5,0.4,Iris-setosa\n', '23,4.6,3.6,1.0,0.2,Iris-setosa\n', '24,5.1,3.3,1.7,0.5,Iris-setosa\n', '25,4.8,3.4,1.9,0.2,Iris-setosa\n', '26,5.0,3.0,1.6,0.2,Iris-setosa\n', '2

In [ ]:
ok.check('e03_2.py')

# 3 Remoção de Cabeçalho e Contagem de Linhas

Utilizando a mesma variável `d0`, agora remova o cabeçalho (que deve ser o primeiro elemento da lista), e conte as linhas de dados. Grave o total de linhas numa variável de nome `total`.

In [ ]:
d0 = d0[1:]
total = len(d0)
print(total)

150


In [ ]:
ok.check('e03_3.py')

# 4 Remoção de Novas Linhas

Crie uma nova lista numa variável de nome `d1` onde cada elemento de `d1` corresponda à versão do mesmo elemento em `d0`, removendo o caractere de nova linha `\n` que aparece ao final de cada item. Assegure-se de que cada elemento da lista `d1` seja uma string simples (dependendo como você fez o upload, pode acontecer dos elementos estarem codificados, então decodifique caso necessário).

In [ ]:
d1 = []
for i in d0:
  rmv = i[:-1]
  d1.append(rmv)
  print(d1)




['1,5.1,3.5,1.4,0.2,Iris-setosa']
['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa']
['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa']
['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa', '4,4.6,3.1,1.5,0.2,Iris-setosa']
['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa', '4,4.6,3.1,1.5,0.2,Iris-setosa', '5,5.0,3.6,1.4,0.2,Iris-setosa']
['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa', '4,4.6,3.1,1.5,0.2,Iris-setosa', '5,5.0,3.6,1.4,0.2,Iris-setosa', '6,5.4,3.9,1.7,0.4,Iris-setosa']
['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3,4.7,3.2,1.3,0.2,Iris-setosa', '4,4.6,3.1,1.5,0.2,Iris-setosa', '5,5.0,3.6,1.4,0.2,Iris-setosa', '6,5.4,3.9,1.7,0.4,Iris-setosa', '7,4.6,3.4,1.4,0.3,Iris-setosa']
['1,5.1,3.5,1.4,0.2,Iris-setosa', '2,4.9,3.0,1.4,0.2,Iris-setosa', '3

In [ ]:
ok.check('e03_4.py')

# 5 Separação por Vírgulas

Crie uma nova lista em uma variável de nome `d2` onde cada elemento dessa lista seja uma sublista contendo as strings correspondentes a cada dado da string original, usando a vírgula como separador.

Por exemplo, transforme isso:

`'14,4.3,3.0,1.1,0.1,Iris-setosa'`

nisso:

`['14', '4.3', '3.0', '1.1', '0.1', 'Iris-setosa']`

Faça isso para todos elementos, na mesma ordem da lista original, gravando o resultado em `d2`.


In [ ]:
d2 = []
for i in d1:
  Dv = i.split(',')
  d2.append(Dv)
  print(d2)


[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa']]
[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa']]
[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'], ['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa']]
[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'], ['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'], ['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa']]
[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'], ['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'], ['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa'], ['5', '5.0', '3.6', '1.4', '0.2', 'Iris-setosa']]
[['1', '5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], ['2', '4.9', '3.0', '1.4', '0.2', 'Iris-setosa'], ['3', '4.7', '3.2', '1.3', '0.2', 'Iris-setosa'], ['4', '4.6', '3.1', '1.5', '0.2', 'Iris-setosa'], ['5', '5.0', '3.6', '1.4', '0.2', 'Iris-seto

In [ ]:
ok.check('e03_5.py')

# 6 Entradas de Treinamento

Crie uma matriz no formato `array` do NumPy, numa variável de nome `d3`, contendo todos os dados da segunda, terceira, quarta e quinta colunas de `d2` transformados para o formato ponto flutuante (convertendo de string para número). Não inclua nem a primeira coluna (que é o id), nem a última coluna nessa conversão. Essa será a matriz de entradas.

In [ ]:
# Escreva seu código aqui
import numpy as np
d3 = np.zeros((len(d2),4))
for i, l in enumerate(d2):
  #transformar coluna de d2 para o formato ponto flutuante
  d3[i][0]=float(d2[i][1]) #Transformando em ponto flutuante
  d3[i][1]=float(d2[i][2])
  d3[i][2]=float(d2[i][3])
  d3[i][3]=float(d2[i][4])

print(d3)





[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
ok.check('e03_6.py')

# 7 Saídas Desejadas

Crie um `array` do NumPy para as saídas desejadas, no formado _one-hot_. Para isso utilize as strings da última coluna de `d2`, verificando qual espécie de planta se refere cada string:

 `'Iris-setosa'` $\rightarrow$ `[1.0, 0.0, 0.0]`
 
 `'Iris-versicolor'` $\rightarrow$ `[0.0, 1.0, 0.0]`

 `'Iris-virginica'` $\rightarrow$ `[0.0, 0.0, 1.0]`

 Grave o resultado em um `array` do NumPy de nome `d4`, com o mesmo número de linhas de `d3`, onde cada linha de `d4` corresponde ao vetor _one-hot_ da saída desejada da respectiva linha de entradas de `d4`.

In [ ]:
import numpy as np


d4 = np.zeros((len(d3),3))
s = np.array(['Iris-setosa','Iris-versicolor', 'Iris-virginica'])
for i,l in enumerate(d2):
  d4[i]=((s==d2[i][5]).astype(float))
  print(d4)




Streaming output truncated to the last 5000 lines.
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]


In [ ]:
ok.check('e03_7.py')

# 8 Normalização das Entradas

Encontre o valor máximo e mínimo para cada uma das quatro colunas da matriz de entradas. Normalize os valores das entradas no intervalo entre zero e um, salvando o resultado em um `array` do NumPy de nome `d5`.

In [ ]:
# Escreva seu código aqui
import numpy as np
d5 = np.array(d3)
d5 = ((d5-np.min(d5, axis=0))/(np.max(d5, axis=0)-np.min(d5, axis=0)))
print(d5)

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]
 [0.30555556 0.79166667 0.11864407 0.125     ]
 [0.08333333 0.58333333 0.06779661 0.08333333]
 [0.19444444 0.58333333 0.08474576 0.04166667]
 [0.02777778 0.375      0.06779661 0.04166667]
 [0.16666667 0.45833333 0.08474576 0.        ]
 [0.30555556 0.70833333 0.08474576 0.04166667]
 [0.13888889 0.58333333 0.10169492 0.04166667]
 [0.13888889 0.41666667 0.06779661 0.        ]
 [0.         0.41666667 0.01694915 0.        ]
 [0.41666667 0.83333333 0.03389831 0.04166667]
 [0.38888889 1.         0.08474576 0.125     ]
 [0.30555556 0.79166667 0.05084746 0.125     ]
 [0.22222222 0.625      0.06779661 0.08333333]
 [0.38888889 0.75       0.11864407 0.08333333]
 [0.22222222 0.75       0.08474576 0.08333333]
 [0.30555556 0.58333333 0.11864407 0.04166667]
 [0.22222222 

In [ ]:
ok.check('e03_8.py')

# 9 Embaralhamento dos Dados

Misture as linhas dos dados dos valores de entradas de treinamento contidos em `d5` de forma aleatória. Faça o mesmo com as linhas das saídas desejadas em `d4`, de forma a manter a correspondência entre ambos. Chame a `array` resultante de dados de treinamento embaralhado de `x` e a `array` correspondente de saídas desejadas de `y`.

In [ ]:
from numpy.random import shuffle

''' Agp = [] #cria uma lista de agrupamento
for i in range(len(d5)):
  Agp.append([d5[i],d4[i]])
copy = Agp
shuffle(copy)
x = []
y = []
for i in range(len(d5)):
  x.append(copy[i][0])
  y.append(copy[i][1])
 '''
''' total = len(d5)
indices = list(range(total))
np.shuffle(indices)
x = d5(indices)
y = d6(indices) '''

x = d5 
y = d4

t = len(d5)#total
agp = list(range(t))#agrupamento
np.random.shuffle(agp)
x = x[agp,:]
y = y[agp,:]

In [ ]:
ok.check('e03_9.py')

# 10 Separação de Dados de Treinamento e Validação

Separe os pares de dados de treinamento e validação nas proporções 90%/10%, respectivamente. Chame a entrada e saída desejada dos pares de treinamento de `x_train` e `y_train`, e use os nomes `x_test` e `y_test` para os dados de validação. Os dados de validação devem corresponder às linhas finais dos pares de `array` originais `x` e `y`.

In [ ]:
# Escreva seu código aqui
#criando a função de teste e treinamento
''' 
def split_train_test(x,y):
  Tam_x_train = int(len(x)*0.9)
  Tam_y_train = int(len(y)*0.9)
  Tam_x_test = len(x) - Tam_x_train 
  Tam_y_test = len(y) - Tam_y_train '''
  
x_train=x[:-15]
y_train=y[:-15]
x_test=x[-15:]
y_test=y[-15:]



In [ ]:
ok.check('e03_10.py')